project:
  type: website

website:
  title: "LLM Experiments & Insights"
  description: "A collection of projects, experiments, and thoughts exploring the possibilities of large language models."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    code-copy: true

execute:
  freeze: auto
